name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black flake8 pytest

      - name: Run lint (flake8)
        run: |
          if [ -d tests ]; then
            flake8 project tests --ignore=E203,W503 --max-line-length=100
          else
            flake8 project --ignore=E203,W503 --max-line-length=100
          fi

      - name: Run format check (black --check)
        run: |
          if [ -d tests ]; then
            black --check project tests
          else
            black --check project
          fi

      - name: Run tests (pytest)
        run: |
          if [ -d tests ]; then
            pytest -q
          else
            echo "No tests folder found, skipping pytest"
          fi
